repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.0
  hooks:
   - id: terraform_fmt
   - id: terraform_validate
- repo: https://github.com/bridgecrewio/checkov
  rev: 3.0.0
  hooks:
   - id: checkov
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.0
  hooks:
   - id: gitleaks